### ISSUE TITLE
基本需求

### ISSUE THREAD

**Issue by DynamicLoader** [GCScholarInsight/Index_Serialize_Test#1]
看了代码，有进展，但是比较demo。

期望的是，有一个抽象的类，这个类实现存储结构，比如B树，Key是主键，一定支持使用Key查找：

```C++
template<typename TKey,typename TObj>
class Storage;
```

这个 `Storage` 类应该在内部处理多层**在磁盘中的** `map`，使得对外暴露的接口和内存中的 `map` 相似（能支持常见的增删改查），Obj 会自行提供序列化实现，无需 `Storage` 关心。

更进一步地，如果想要加入其他参数，比如最大索引层数，可以使用类似下面的声明：

- 静态实现（通过模板参数指定）：
```C++
template<typename TKey,typename TObj, uint8_t maxIndexLevel>
class Storage;
```

- 动态实现（通过构造函数参数指定）：
```C++
template<typename TKey,typename TObj>
class Storage{
    public:
        Storage(uint8_t maxIndexLevel, ...);
}
```

采用何种实现，应该根据实际衡量。

**Comment by DynamicLoader** [comment]
- 另，计划后期索引也使用这类进行存储，但是可能存在单键多值映射（即 multimap），所以内部应该支持到 std::multimap。

一种比较舒服的实现方法是，写一个基类，如:
```C++
template<typename TKey,typename TObj, class Impl>
class StorageBase;
```
这个基类可以 handle 大部分的工作，( std::map 和 std:multimap 的区别不多，大部分方法是公共的)，然后针对不同的 `Impl`，利用 if constexpr (C++17) 以及 std::enable_if (C++11) 执行不同的操作，进行特化版本函数的编写，或者在特化的版本单独编写：

- 利用[偏特化](https://blog.csdn.net/K346K346/article/details/82179205)实现：
```C++
template<typename TKey,TObj,uint8_t impl>
class Storage; // 基本声明，可以用 type_trait 或 concept 保护

// 我们假定 impl 值为 1 => map, 2 => multimap, 3 => unordered_map 

// map
template<typename TKey,typename TObj>
class Storage<TKey,TObj,1> : public StorageBase<TKey,TObj,std::map<TKey,TObj>>{}

// multimap
template<typename TKey,typename TObj>
class Storage<TKey,TObj,2> : public StorageBase<TKey,TObj,std::multimap<TKey,TObj>>{}

// unordered map
template<typename TKey,typename TObj>
class Storage<TKey,TObj,3> : public StorageBase<TKey,TObj,std::unordered_map<TKey,TObj>>{}
```

- 也可以使用正常类实现，语法不同罢了。

**Comment by perfsakuya** [comment]
明白意思，不过现在有两种可供选择的方向：

- 第一种是维持现有结构不变，继续用map实现基本功能，缺点是需要在序列化上做各种优化。

- 第二种是改用类MyISAM/InnoDB的结构，用B+树实现，有成熟的轮子，稍作修改即可。不过索引得另外处理，或者魔改一下树结构。

具体方案可以再根据需求讨论，这周末比较忙，争取下周实现实验性版本。
